---

- name: install Python 2 # By default Ubuntu 16.04 doesn't have preinstalled python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    
- name: gather facts
  become: false
  setup:

- name: install htop
  package: name=htop state=latest update_cache=yes

- name: set UTC timezone
  timezone: name=UTC

- name: enable timesyncd service
  service: name=systemd-timesyncd state=started enabled=yes

- name: ensure a locale exists
  locale_gen: name=en_US.UTF-8

- name: set locale variables
  become: false
  lineinfile: >
    dest="{{ ansible_env.HOME }}/.bashrc"
    line="export {{ item }}"
    insertafter=EOF
    state=present
  with_items:
    - "LANG=en_US.UTF-8"
    - "LANGUAGE=en_US:en"
    - "LC_ALL=en_US.UTF-8"